.TH gfs2_lockgather 8

.SH NAME
gfs2_lockgather - Gathers data for diagnosing GFS2 locking issues

.SH SYNOPSIS
.B gfs2_lockgather
[\fIOPTIONS\fR]

.SH DESCRIPTION
gfs2_lockgather will gather data that is useful for diagnosing performance and locking issues 
involving GFS2 filesystems. The script gathers basic system and cluster data such as rpm output, 
kernel version, thread dumps from all processes, and 2 passes of glock and DLM locking data. After
the data is gathered it is stored in a tarball under /tmp. The script can be invoked to gather
data from a single node, or to gather data from all nodes via ssh.     
.SH OPTIONS
.TP
\fB-h, --help, --info\fP
Display help and usage information.
.TP
\fB-q, --quiet\fP
Quiet mode. Run with output supressed.
.TP
\fB-a, --allnodes\fP
Gather data from all nodes via ssh.

